from django.urls import path
from controledegastos.views import index, indexmeses, login, register, createorcamento, createcategoria, createdespesa, createlugar, createprevista, createcredito, createdespesacredito, orcamento, lugar, despesa, categoria, prevista, despesacredito, orcamentos, lugares, categorias, previstas, creditos, despesascredito, deleteorcamento, deletedespesa, deletecategoria, deletelugar, deleteprevista, deletecartao, deletedespesacredito, editorcamento, editdespesa, editcategoria, editlugar, editprevista, editcredito, editdespesacredito, logout, editperfil, perfil, ativar_conta, ative_seu_email
app_name = 'controledegastos'

urlpatterns = [
    path('', index, name='index'),
    path('<int:mes>/<int:ano>/', indexmeses, name='indexmeses'),
    path('orcamentos/', orcamentos, name='orcamentos'),
    path('categorias/', categorias, name='categorias'),
    path('lugares/', lugares, name='lugares'),
    path('previstas/', previstas, name='previstas'),
    path('creditos/', creditos, name='creditos'),
    path('despesascredito/<int:credito_id>/', despesascredito, name='despesascredito'),
    path('orcamento/<int:orcamento_id>/', orcamento, name='orcamento'),
    path('lugar/<int:lugar_id>/', lugar, name='lugar'),
    path('despesa/<int:despesa_id>/', despesa, name='despesa'),
    path('categoria/<int:categoria_id>/', categoria, name='categoria'),
    path('prevista/<int:prevista_id>/', prevista, name='prevista'),
    path('despesacredito/<int:despesa_id>/', despesacredito, name='despesacredito'),
    path('criar/orcamento/', createorcamento, name='criarorcamento'),
    path('criar/lugar/', createlugar, name='criarlugar'),
    path('criar/categoria/', createcategoria, name='criarcategoria'),
    path('criar/despesa/', createdespesa, name='criardespesa'),
    path('criar/prevista/', createprevista, name='criarprevista'),
    path('criar/credito/', createcredito, name='criarcartao'),
    path('criar/despesacredito/', createdespesacredito, name='criardespesacredito'),
    path('deletar/orcamento/<int:orcamento_id>/', deleteorcamento, name='deletarorcamento'),
    path('deletar/despesa/<int:despesa_id>/', deletedespesa, name='deletardespesa'),
    path('deletar/categoria/<int:categoria_id>/', deletecategoria, name='deletarcategoria'),
    path('deletar/lugar/<int:lugar_id>/', deletelugar, name='deletarlugar'),
    path('deletar/prevista/<int:prevista_id>/', deleteprevista, name='deletarprevista'),
    path('deletar/credito/<int:cartao_id>/', deletecartao, name='deletarcartao'),
    path('deletar/despesacredito/<int:despesa_id>/', deletedespesacredito, name='deletardespesacredito'),
    path('editar/orcamento/<int:orcamento_id>/', editorcamento, name='editarorcamento'),
    path('editar/despesa/<int:despesa_id>/', editdespesa, name='editardespesa'),
    path('editar/categoria/<int:categoria_id>/', editcategoria, name='editarcategoria'),
    path('editar/lugar/<int:lugar_id>/', editlugar, name='editarlugar'),
    path('editar/prevista/<int:prevista_id>/', editprevista, name='editarprevista'),
    path('editar/credito/<int:cartao_id>/', editcredito, name='editarcartao'),
    path('editar/despesacredito/<int:despesa_id>/', editdespesacredito, name='editardespesacredito'),
    path('ativar/<uidb64>/<token>/', ativar_conta, name='ativar_conta'),
    path('ative-seu-email/<uid>/', ative_seu_email, name='ative_email'),
    path('login/', login, name='login'),
    path('cadastro/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('editar/perfil/', editperfil, name='editperfil'),
    path('perfil/', perfil, name='perfil'),
]